language: haskell

os:
#  - osx
  - linux

ghc:
  - "7.10"
  - 7.8
  - 7.6
  - 7.4

before_install:
  - git submodule update --init --recursive

install:
    - cabal install

script: 
    #- make test | grep "#f"; [ $? == 1 ]
    - zepto
    - make test
